//save varibles for store
export const SET_INSTRUMENTS_ACTIVE = 'SET_INSTRUMENTS_ACTIVE'
export const UPDATE_INSTRUMENTS_ACTIVE = 'UPDATE_INSTRUMENTS_ACTIVE'
export const SET_ACTIVE_INSTRUMENT = 'SET_ACTIVE_INSTRUMENT'
export const SET_HISTORY_ORDERS = 'SET_HISTORY_ORDERS'

export const LOAD_HISTORY_ORDERS = 'LOAD_HISTORY_ORDERS'
